import numpy as np
import cv2 as cv
from matplotlib import pyplot as py
import RunCameras as rc
import Tracker as tr


def main():
    #initiate and run cameras
    rc.cameras()

    #list to import the outputs generated by cameras function
    camOutputList = ['output1.mp4v', 'output2.mp4v', 'output3.mp4v', 'output4.mp4v', 'output5.mp4v', 'output6.mp4v']

    tr.backgroundMask(camOutputList[1])

main()